language : node_js

cache:
  npm: false
  directories:
    - "~/.pnpm-store"

before_install:
  - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7.0.0-rc.3
  - pnpm config set store-dir ~/.pnpm-store

install:
  - pnpm install

node_js:
  - "14"

script:
  - pnpm test

before_deploy:
  - "pnpm doc"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  on:
    branch: master
