export { default as noop } from './noop';
export { default as set } from './set';
export { default as get } from './get';
export { default as nextTick } from './next-tick';
export { default as toggle } from './toogle';
export { default as singleton, SINGLETON_KEY } from './singleton';
export { default as shallowEqual } from './shallow-equal';
export { default as equal } from './equal';
export { default as incrementId } from './increment-id';
export { default as after } from './after';
export { default as before } from './before';
export { default as memoizeWith } from './memoize-with';
export { prefSetTimeout, clearPrefTimeout } from './pref-setTimeout';
export { prefSetInterval, clearPrefSetInterval } from './pref-setInterval';
export { default as debounce } from 'lodash.debounce';
export { default as throttle } from 'lodash.throttle';
export { default as cloneDeep } from 'lodash.clonedeep';
export { default as once } from './once';
export { default as pref } from './pref';
export { default as tryCatch } from './try-catch';

export { default as curry } from './curry';
export { default as uncurry } from './uncurry';
export { default as compose } from './compose';
export { default as pipe } from './pipe';
